dist: xenial
language: cpp
os:
  - linux
  - osx
env:
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7.3

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda info
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q conda-build anaconda-client
  - conda create -q -n test-environment python=$PYTHON_VERSION
  - source activate test-environment

script:
  - conda build conda.recipe --python $PYTHON_VERSION
  - conda install --use-local ecell4_base

deploy:
  - provider: script
    script: anaconda -t $CONDA_UPLOAD_TOKEN upload /*/travis/miniconda/conda-bld/*/*.tar.bz2
    on:
      tags: true
    skip_cleanup: true
